version: '3'

services:
  php:
    image: yosmanyga/php
    container_name: yosmanyga_satis_builder_php
    volumes:
      - ./php/php_dev.ini:/usr/local/etc/php/php.ini
      - ../:/var/www/
    networks:
      - development
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      PATH: $PATH:/var/www/vendor/bin
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /var/www
    user: $DOCKER_USER

networks:
  development:
    external: true